services:
  phpapache:
    image: php:8.0-apache
    container_name: php8_apache_app
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    ports:
      - "5050:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - compose-net
  
  mysql:
    image: mysql:8.0
    container_name: mysql8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
    - compose-net

networks:
  compose-net:
    driver: bridge

volumes:
  src:
  mysql_data: